/**
 * CRUD scaffolder.
 *
 * Generates standards-compliant route, service, and component files for an
 * entity definition.  Zero external dependencies -- pure string template
 * generation with file writes via node:fs.
 */

import { writeFile, mkdir } from 'node:fs/promises';
import { join } from 'node:path';

/* ---------- Naming helpers ---------------------------------------------- */

/** "Task" -> "task" */
function lowerFirst(str) {
  return str.charAt(0).toLowerCase() + str.slice(1);
}

/** "tasks" -> "Tasks" */
function pascalCase(str) {
  return str.charAt(0).toUpperCase() + str.slice(1);
}

/** "Task" -> "task" (kebab-case for single words, handles PascalCase) */
function toKebab(str) {
  return str
    .replace(/([a-z])([A-Z])/g, '$1-$2')
    .replace(/\s+/g, '-')
    .toLowerCase();
}

/* ---------- Template: server route -------------------------------------- */

function generateRouteFile(entity) {
  const { name, pluralName, fields } = entity;
  const funcPrefix = name; // e.g. "Task"
  const lower = lowerFirst(name); // e.g. "task"

  // Build validation rules for required fields
  const requiredFields = fields.filter((f) => f.required);
  const validationBlock = requiredFields.length
    ? requiredFields
        .map((f) => {
          const checks = [`required: true`];
          if (f.type === 'string') checks.push(`type: 'string'`);
          if (f.type === 'number') checks.push(`type: 'number'`);
          return `    ${f.name}: { ${checks.join(', ')} }`;
        })
        .join(',\n')
    : '';

  // Build default values for create
  const defaultAssignments = fields
    .filter((f) => f.default !== undefined)
    .map((f) => {
      const val = typeof f.default === 'string' ? `'${f.default}'` : f.default;
      return `    ${f.name}: body.${f.name} !== undefined ? body.${f.name} : ${val},`;
    })
    .join('\n');

  const nonDefaultFields = fields
    .filter((f) => f.default === undefined)
    .map((f) => `    ${f.name}: body.${f.name},`)
    .join('\n');

  return `/**
 * CRUD routes for ${pluralName}.
 * Auto-generated by scaffold utility.
 */

import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { join } from 'node:path';
import { randomUUID } from 'node:crypto';

const DATA_DIR = join(process.cwd(), 'data');
const DATA_FILE = join(DATA_DIR, '${pluralName}.json');

async function loadAll() {
  try {
    const raw = await readFile(DATA_FILE, 'utf8');
    return JSON.parse(raw);
  } catch {
    return [];
  }
}

async function saveAll(records) {
  await mkdir(DATA_DIR, { recursive: true });
  await writeFile(DATA_FILE, JSON.stringify(records, null, 2) + '\\n');
}

function validate(body, rules) {
  const errors = [];
  for (const [field, check] of Object.entries(rules)) {
    const value = body[field];
    if (check.required && (value === undefined || value === null || value === '')) {
      errors.push(\`\${field} is required.\`);
    }
    if (check.type && value !== undefined && value !== null && typeof value !== check.type) {
      errors.push(\`\${field} must be a \${check.type}.\`);
    }
  }
  return errors;
}

async function list${funcPrefix}s(req, res) {
  const records = await loadAll();
  res.json(records);
}

async function get${funcPrefix}(req, res) {
  const records = await loadAll();
  const record = records.find((r) => r.id === req.params.id);
  if (!record) {
    return res.status(404).json({ error: { code: 'NOT_FOUND', message: '${name} not found.' } });
  }
  res.json(record);
}

async function create${funcPrefix}(req, res) {
  const body = req.body || {};
${validationBlock ? `  const errors = validate(body, {\n${validationBlock}\n  });\n  if (errors.length) {\n    return res.status(400).json({ error: { code: 'VALIDATION_ERROR', message: errors[0] } });\n  }\n` : ''}
  const record = {
    id: randomUUID(),
${nonDefaultFields}
${defaultAssignments}
    createdAt: new Date().toISOString(),
  };

  const records = await loadAll();
  records.push(record);
  await saveAll(records);
  res.status(201).json(record);
}

async function update${funcPrefix}(req, res) {
  const records = await loadAll();
  const index = records.findIndex((r) => r.id === req.params.id);
  if (index === -1) {
    return res.status(404).json({ error: { code: 'NOT_FOUND', message: '${name} not found.' } });
  }

  const body = req.body || {};
${validationBlock ? `  const errors = validate(body, {\n${validationBlock}\n  });\n  if (errors.length) {\n    return res.status(400).json({ error: { code: 'VALIDATION_ERROR', message: errors[0] } });\n  }\n` : ''}
  const updated = { ...records[index], ...body, id: records[index].id };
  records[index] = updated;
  await saveAll(records);
  res.json(updated);
}

async function delete${funcPrefix}(req, res) {
  const records = await loadAll();
  const index = records.findIndex((r) => r.id === req.params.id);
  if (index === -1) {
    return res.status(404).json({ error: { code: 'NOT_FOUND', message: '${name} not found.' } });
  }

  records.splice(index, 1);
  await saveAll(records);
  res.status(204).end();
}

export function register${funcPrefix}Routes(router) {
  router.get('/${pluralName}', list${funcPrefix}s);
  router.get('/${pluralName}/:id', get${funcPrefix});
  router.post('/${pluralName}', create${funcPrefix});
  router.put('/${pluralName}/:id', update${funcPrefix});
  router.delete('/${pluralName}/:id', delete${funcPrefix});
}
`;
}

/* ---------- Template: frontend API service ------------------------------ */

function generateServiceFile(entity) {
  const { name, pluralName } = entity;
  const pluralPascal = pascalCase(pluralName);

  return `/**
 * API client for ${pluralName}.
 * Auto-generated by scaffold utility.
 */

const BASE = '/api/v1';

export async function fetch${pluralPascal}() {
  const res = await fetch(\`\${BASE}/${pluralName}\`);
  if (!res.ok) throw new Error(\`Failed to fetch ${pluralName}: \${res.status}\`);
  return res.json();
}

export async function fetch${name}(id) {
  const res = await fetch(\`\${BASE}/${pluralName}/\${id}\`);
  if (!res.ok) throw new Error(\`Failed to fetch ${lowerFirst(name)}: \${res.status}\`);
  return res.json();
}

export async function create${name}(data) {
  const res = await fetch(\`\${BASE}/${pluralName}\`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(data),
  });
  if (!res.ok) throw new Error(\`Failed to create ${lowerFirst(name)}: \${res.status}\`);
  return res.json();
}

export async function update${name}(id, data) {
  const res = await fetch(\`\${BASE}/${pluralName}/\${id}\`, {
    method: 'PUT',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(data),
  });
  if (!res.ok) throw new Error(\`Failed to update ${lowerFirst(name)}: \${res.status}\`);
  return res.json();
}

export async function delete${name}(id) {
  const res = await fetch(\`\${BASE}/${pluralName}/\${id}\`, {
    method: 'DELETE',
  });
  if (!res.ok) throw new Error(\`Failed to delete ${lowerFirst(name)}: \${res.status}\`);
}
`;
}

/* ---------- Template: card component ------------------------------------ */

function generateCardFile(entity) {
  const { name, fields } = entity;
  const kebab = toKebab(name);
  const lower = lowerFirst(name);

  // Pick key display fields (first 3 non-id fields)
  const displayFields = fields.slice(0, 3);

  const fieldElements = displayFields
    .map((f) => {
      if (f.type === 'enum') {
        return `
  const ${f.name}Badge = document.createElement('span');
  ${f.name}Badge.className = 'badge badge--' + (item.${f.name} || 'default');
  ${f.name}Badge.textContent = item.${f.name} || '';`;
      }
      return `
  const ${f.name}Element = document.createElement('p');
  ${f.name}Element.className = '${kebab}-card__${f.name}';
  ${f.name}Element.textContent = item.${f.name} || '';`;
    })
    .join('\n');

  const appendList = displayFields
    .map((f) => (f.type === 'enum' ? `${f.name}Badge` : `${f.name}Element`))
    .join(', ');

  return `/**
 * Card component for ${name}.
 * Auto-generated by scaffold utility.
 */

export function create${name}Card(item) {
  const card = document.createElement('article');
  card.className = '${kebab}-card';
  card.dataset.id = item.id;
  card.style.cursor = 'pointer';
${fieldElements}

  card.append(${appendList});
  return card;
}
`;
}

/* ---------- Template: form component ------------------------------------ */

function generateFormFile(entity) {
  const { name, fields } = entity;
  const kebab = toKebab(name);

  const fieldInputs = fields
    .map((f) => {
      const required = f.required ? ' required' : '';
      const label = `
    const ${f.name}Label = document.createElement('label');
    ${f.name}Label.textContent = '${pascalCase(f.name)}';
    ${f.name}Label.setAttribute('for', '${f.name}');`;

      if (f.type === 'enum') {
        const options = (f.options || [])
          .map((o) => {
            return `
      const ${f.name}Opt${pascalCase(o.replace(/[^a-zA-Z0-9]/g, ''))} = document.createElement('option');
      ${f.name}Opt${pascalCase(o.replace(/[^a-zA-Z0-9]/g, ''))}.value = '${o}';
      ${f.name}Opt${pascalCase(o.replace(/[^a-zA-Z0-9]/g, ''))}.textContent = '${o}';
      ${f.name}Select.append(${f.name}Opt${pascalCase(o.replace(/[^a-zA-Z0-9]/g, ''))});`;
          })
          .join('');

        return `${label}
    const ${f.name}Select = document.createElement('select');
    ${f.name}Select.name = '${f.name}';
    ${f.name}Select.id = '${f.name}';${options}
    if (item && item.${f.name}) ${f.name}Select.value = item.${f.name};${f.default !== undefined ? ` else ${f.name}Select.value = '${f.default}';` : ''}
    const ${f.name}Group = document.createElement('div');
    ${f.name}Group.className = 'form-group';
    ${f.name}Group.append(${f.name}Label, ${f.name}Select);`;
      }

      if (f.type === 'number') {
        return `${label}
    const ${f.name}Input = document.createElement('input');
    ${f.name}Input.type = 'number';
    ${f.name}Input.name = '${f.name}';
    ${f.name}Input.id = '${f.name}';${required ? `\n    ${f.name}Input.required = true;` : ''}
    if (item && item.${f.name} !== undefined) ${f.name}Input.value = item.${f.name};${f.default !== undefined ? ` else ${f.name}Input.value = '${f.default}';` : ''}
    const ${f.name}Group = document.createElement('div');
    ${f.name}Group.className = 'form-group';
    ${f.name}Group.append(${f.name}Label, ${f.name}Input);`;
      }

      if (f.type === 'boolean') {
        return `${label}
    const ${f.name}Input = document.createElement('input');
    ${f.name}Input.type = 'checkbox';
    ${f.name}Input.name = '${f.name}';
    ${f.name}Input.id = '${f.name}';
    if (item && item.${f.name}) ${f.name}Input.checked = true;
    const ${f.name}Group = document.createElement('div');
    ${f.name}Group.className = 'form-group form-group--checkbox';
    ${f.name}Group.append(${f.name}Input, ${f.name}Label);`;
      }

      // Default: text input (string, date, etc.)
      const inputType = f.type === 'date' ? 'date' : 'text';
      return `${label}
    const ${f.name}Input = document.createElement('input');
    ${f.name}Input.type = '${inputType}';
    ${f.name}Input.name = '${f.name}';
    ${f.name}Input.id = '${f.name}';${required ? `\n    ${f.name}Input.required = true;` : ''}
    if (item && item.${f.name}) ${f.name}Input.value = item.${f.name};
    const ${f.name}Group = document.createElement('div');
    ${f.name}Group.className = 'form-group';
    ${f.name}Group.append(${f.name}Label, ${f.name}Input);`;
    })
    .join('\n');

  const groupAppendList = fields.map((f) => `${f.name}Group`).join(', ');

  // Gather form data: handle select vs input vs checkbox
  const gatherLines = fields
    .map((f) => {
      if (f.type === 'enum') {
        return `      ${f.name}: form.querySelector('[name="${f.name}"]').value,`;
      }
      if (f.type === 'boolean') {
        return `      ${f.name}: form.querySelector('[name="${f.name}"]').checked,`;
      }
      if (f.type === 'number') {
        return `      ${f.name}: Number(form.querySelector('[name="${f.name}"]').value),`;
      }
      return `      ${f.name}: form.querySelector('[name="${f.name}"]').value,`;
    })
    .join('\n');

  // Required field validation
  const requiredChecks = fields
    .filter((f) => f.required)
    .map((f) => {
      if (f.type === 'string') {
        return `    if (!data.${f.name} || !data.${f.name}.trim()) { alert('${pascalCase(f.name)} is required.'); return; }`;
      }
      return `    if (data.${f.name} === undefined || data.${f.name} === null || data.${f.name} === '') { alert('${pascalCase(f.name)} is required.'); return; }`;
    })
    .join('\n');

  return `/**
 * Form component for ${name}.
 * Auto-generated by scaffold utility.
 */

export function create${name}Form({ item, onSubmit } = {}) {
  const form = document.createElement('form');
  form.className = '${kebab}-form';
${fieldInputs}

    const submitButton = document.createElement('button');
    submitButton.type = 'submit';
    submitButton.className = 'btn btn--primary';
    submitButton.textContent = item ? 'Update' : 'Create';

    form.append(${groupAppendList}, submitButton);

    form.addEventListener('submit', (event) => {
      event.preventDefault();
      const data = {
${gatherLines}
      };
${requiredChecks}
      if (onSubmit) onSubmit(data);
    });

    return form;
}
`;
}

/* ---------- Template: detail component ---------------------------------- */

function generateDetailFile(entity) {
  const { name, fields } = entity;
  const kebab = toKebab(name);

  const fieldRows = fields
    .map(
      (f) => `
  const ${f.name}Row = document.createElement('div');
  ${f.name}Row.className = '${kebab}-detail__row';
  const ${f.name}Label = document.createElement('strong');
  ${f.name}Label.textContent = '${pascalCase(f.name)}: ';
  const ${f.name}Value = document.createElement('span');
  ${f.name}Value.textContent = item.${f.name} !== undefined ? String(item.${f.name}) : '';
  ${f.name}Row.append(${f.name}Label, ${f.name}Value);`,
    )
    .join('\n');

  const rowAppendList = fields.map((f) => `${f.name}Row`).join(', ');

  return `/**
 * Detail component for ${name}.
 * Auto-generated by scaffold utility.
 */

export function create${name}Detail({ item, onEdit, onDelete } = {}) {
  const container = document.createElement('section');
  container.className = '${kebab}-detail';

  const heading = document.createElement('h2');
  heading.textContent = item.${fields[0]?.name || 'id'} || '${name} Detail';
${fieldRows}

  const actions = document.createElement('div');
  actions.className = '${kebab}-detail__actions';

  const editButton = document.createElement('button');
  editButton.className = 'btn btn--primary';
  editButton.textContent = 'Edit';
  editButton.addEventListener('click', () => { if (onEdit) onEdit(item); });

  const deleteButton = document.createElement('button');
  deleteButton.className = 'btn btn--danger';
  deleteButton.textContent = 'Delete';
  deleteButton.addEventListener('click', () => {
    if (confirm('Are you sure you want to delete this ${lowerFirst(name)}?')) {
      if (onDelete) onDelete(item);
    }
  });

  actions.append(editButton, deleteButton);
  container.append(heading, ${rowAppendList}, actions);
  return container;
}
`;
}

/* ---------- CSS block --------------------------------------------------- */

function generateCssBlock(entity) {
  const kebab = toKebab(entity.name);

  return `/* ${entity.name} components -- auto-generated by scaffold utility */

.${kebab}-card {
  background: var(--color-surface);
  border: 1px solid var(--color-border);
  border-radius: var(--radius);
  padding: calc(var(--spacing-unit) * 2);
  cursor: pointer;
  transition: border-color 0.2s;
}
.${kebab}-card:hover {
  border-color: var(--color-accent);
}

.${kebab}-form {
  display: flex;
  flex-direction: column;
  gap: calc(var(--spacing-unit) * 2);
  max-width: 32rem;
}
.${kebab}-form .form-group {
  display: flex;
  flex-direction: column;
  gap: calc(var(--spacing-unit) * 0.5);
}
.${kebab}-form .form-group--checkbox {
  flex-direction: row;
  align-items: center;
}
.${kebab}-form label {
  font-size: var(--font-size-sm);
  color: var(--color-text-muted);
}
.${kebab}-form input,
.${kebab}-form select {
  background: var(--color-primary-light);
  color: var(--color-text);
  border: 1px solid var(--color-border);
  border-radius: var(--radius);
  padding: calc(var(--spacing-unit) * 1.5);
  font-size: var(--font-size-base);
}
.${kebab}-form input:focus,
.${kebab}-form select:focus {
  outline: none;
  border-color: var(--color-accent);
}

.${kebab}-detail {
  max-width: 40rem;
}
.${kebab}-detail h2 {
  color: var(--color-accent);
  margin-bottom: calc(var(--spacing-unit) * 2);
}
.${kebab}-detail__row {
  padding: var(--spacing-unit) 0;
  border-bottom: 1px solid var(--color-border);
}
.${kebab}-detail__row strong {
  color: var(--color-text-muted);
  margin-right: var(--spacing-unit);
}
.${kebab}-detail__actions {
  display: flex;
  gap: var(--spacing-unit);
  margin-top: calc(var(--spacing-unit) * 3);
}

.btn {
  padding: calc(var(--spacing-unit) * 1.5) calc(var(--spacing-unit) * 3);
  border: none;
  border-radius: var(--radius);
  font-size: var(--font-size-base);
  cursor: pointer;
  transition: background 0.2s;
}
.btn--primary {
  background: var(--color-accent);
  color: var(--color-primary);
}
.btn--primary:hover {
  background: var(--color-accent-hover);
}
.btn--danger {
  background: var(--color-error);
  color: var(--color-text);
}
.btn--danger:hover {
  background: #dc2626;
}
`;
}

/* ---------- Public API -------------------------------------------------- */

/**
 * Scaffold CRUD files for a single entity.
 *
 * @param {object} entity       - { name, pluralName, fields: [...] }
 * @param {string} projectRoot  - absolute path to project root
 * @returns {Promise<{files: string[], css: string}>}
 */
export async function scaffoldEntity(entity, projectRoot) {
  if (!entity || !entity.name || !entity.pluralName || !Array.isArray(entity.fields)) {
    throw new TypeError('entity must have name, pluralName, and fields array');
  }
  if (!projectRoot) {
    throw new TypeError('projectRoot is required');
  }

  const kebab = toKebab(entity.name);
  const files = [];

  // Ensure directories exist
  const dirs = [
    join(projectRoot, 'src', 'server', 'routes'),
    join(projectRoot, 'src', 'public', 'js', 'services'),
    join(projectRoot, 'src', 'public', 'js', 'components'),
  ];
  for (const dir of dirs) {
    await mkdir(dir, { recursive: true });
  }

  // 1. Server route
  const routePath = join(projectRoot, 'src', 'server', 'routes', `${entity.pluralName}.mjs`);
  await writeFile(routePath, generateRouteFile(entity));
  files.push(`src/server/routes/${entity.pluralName}.mjs`);

  // 2. Frontend API service
  const servicePath = join(projectRoot, 'src', 'public', 'js', 'services', `${entity.pluralName}-api.mjs`);
  await writeFile(servicePath, generateServiceFile(entity));
  files.push(`src/public/js/services/${entity.pluralName}-api.mjs`);

  // 3. Card component
  const cardPath = join(projectRoot, 'src', 'public', 'js', 'components', `${kebab}-card.mjs`);
  await writeFile(cardPath, generateCardFile(entity));
  files.push(`src/public/js/components/${kebab}-card.mjs`);

  // 4. Form component
  const formPath = join(projectRoot, 'src', 'public', 'js', 'components', `${kebab}-form.mjs`);
  await writeFile(formPath, generateFormFile(entity));
  files.push(`src/public/js/components/${kebab}-form.mjs`);

  // 5. Detail component
  const detailPath = join(projectRoot, 'src', 'public', 'js', 'components', `${kebab}-detail.mjs`);
  await writeFile(detailPath, generateDetailFile(entity));
  files.push(`src/public/js/components/${kebab}-detail.mjs`);

  // 6. CSS block (returned, not written)
  const css = generateCssBlock(entity);

  return { files, css };
}

/**
 * Scaffold CRUD files for multiple entities and return a server registration snippet.
 *
 * @param {Array<object>} entities   - array of entity definitions
 * @param {string} projectRoot       - absolute path to project root
 * @returns {Promise<{allFiles: string[], cssBlocks: string[], registrationSnippet: string}>}
 */
export async function scaffoldAll(entities, projectRoot) {
  if (!Array.isArray(entities) || entities.length === 0) {
    throw new TypeError('entities must be a non-empty array');
  }

  const allFiles = [];
  const cssBlocks = [];

  for (const entity of entities) {
    const result = await scaffoldEntity(entity, projectRoot);
    allFiles.push(...result.files);
    cssBlocks.push(result.css);
  }

  // Generate registration snippet for src/server/index.mjs
  const imports = entities
    .map(
      (e) =>
        `import { register${e.name}Routes } from './routes/${e.pluralName}.mjs';`,
    )
    .join('\n');

  const mounts = entities
    .map((e) => `register${e.name}Routes(apiRouter);`)
    .join('\n');

  const registrationSnippet = `// --- Auto-generated route registration ---
${imports}

// Mount on your apiRouter (after creating it with Router()):
${mounts}`;

  return { allFiles, cssBlocks, registrationSnippet };
}
