/**
 * CRUD routes for templates.
 * Auto-generated by scaffold utility.
 */

import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { join } from 'node:path';
import { randomUUID } from 'node:crypto';

const DATA_DIR = join(process.cwd(), 'data');
const DATA_FILE = join(DATA_DIR, 'templates.json');

async function loadAll() {
  try {
    const raw = await readFile(DATA_FILE, 'utf8');
    return JSON.parse(raw);
  } catch {
    return [];
  }
}

async function saveAll(records) {
  await mkdir(DATA_DIR, { recursive: true });
  await writeFile(DATA_FILE, JSON.stringify(records, null, 2) + '\n');
}

function validate(body, rules) {
  const errors = [];
  for (const [field, check] of Object.entries(rules)) {
    const value = body[field];
    if (check.required && (value === undefined || value === null || value === '')) {
      errors.push(`${field} is required.`);
    }
    if (check.type && value !== undefined && value !== null && typeof value !== check.type) {
      errors.push(`${field} must be a ${check.type}.`);
    }
  }
  return errors;
}

async function listTemplates(req, res) {
  const records = await loadAll();
  res.json(records);
}

async function getTemplate(req, res) {
  const records = await loadAll();
  const record = records.find((r) => r.id === req.params.id);
  if (!record) {
    return res.status(404).json({ error: { code: 'NOT_FOUND', message: 'Template not found.' } });
  }
  res.json(record);
}

async function createTemplate(req, res) {
  const body = req.body || {};
  const errors = validate(body, {
    name: { required: true, type: 'string' },
    content: { required: true, type: 'string' }
  });
  if (errors.length) {
    return res.status(400).json({ error: { code: 'VALIDATION_ERROR', message: errors[0] } });
  }

  const record = {
    id: randomUUID(),
    name: body.name,
    content: body.content,
    category: body.category !== undefined ? body.category : 'other',
    createdAt: new Date().toISOString(),
  };

  const records = await loadAll();
  records.push(record);
  await saveAll(records);
  res.status(201).json(record);
}

async function updateTemplate(req, res) {
  const records = await loadAll();
  const index = records.findIndex((r) => r.id === req.params.id);
  if (index === -1) {
    return res.status(404).json({ error: { code: 'NOT_FOUND', message: 'Template not found.' } });
  }

  const body = req.body || {};
  const errors = validate(body, {
    name: { required: true, type: 'string' },
    content: { required: true, type: 'string' }
  });
  if (errors.length) {
    return res.status(400).json({ error: { code: 'VALIDATION_ERROR', message: errors[0] } });
  }

  const updated = { ...records[index], ...body, id: records[index].id };
  records[index] = updated;
  await saveAll(records);
  res.json(updated);
}

async function deleteTemplate(req, res) {
  const records = await loadAll();
  const index = records.findIndex((r) => r.id === req.params.id);
  if (index === -1) {
    return res.status(404).json({ error: { code: 'NOT_FOUND', message: 'Template not found.' } });
  }

  records.splice(index, 1);
  await saveAll(records);
  res.status(204).end();
}

export function registerTemplateRoutes(router) {
  router.get('/templates', listTemplates);
  router.get('/templates/:id', getTemplate);
  router.post('/templates', createTemplate);
  router.put('/templates/:id', updateTemplate);
  router.delete('/templates/:id', deleteTemplate);
}
